# Form implementation generated from reading ui file 'CopyData.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets ,uic
from PyQt6.QtWidgets import QApplication, QInputDialog, QFileDialog

from copy_paste_ranges import copy_paste_ranges
import threading
import PyPDF2

class Ui_MainWindow(object):        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 61))
        self.label.setObjectName("label")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 30, 361, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.path=str(self.lineEdit.text())
        patt=self.path
        def copydata(self):
            self.list=copy_paste_ranges(patt)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(640, 30, 151, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(copydata)
         
        

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 131, 61))
        self.label_2.setObjectName("label_2")
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(190, 110, 361, 231))
        self.listWidget_2.setObjectName("listWidget_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 370, 131, 61))
        self.label_3.setObjectName("label_3")
 
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(190, 390, 361, 31))
        self.comboBox.setObjectName("comboBox")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 21))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #self.listWidget_2.addItems(self.list)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Path : "))
        self.pushButton.setText(_translate("MainWindow", "CopyData"))
        self.label_2.setText(_translate("MainWindow", "Sheets_names :"))
        self.label_3.setText(_translate("MainWindow", "Temperatures : "))
    
    def button(self):
        self.open_dialog_box()

    def open_dialog_box(self):
        filename=QFileDialog.getOpenFileName()
        self.path=filename[0]


    def open_file(self):
        self.path
        self.txt_pdf_name
        print(self.path)

if __name__== "__main__":
    import sys
    CopyData=QtWidgets.QApplication(sys.argv)
    form=QtWidgets.QWidget()
    ui=Ui_MainWindow()
    ui.setupUi(form)
    form.show()
    sys.exit(CopyData.exec())