# Form implementation generated from reading ui file 'CopyData.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6.QtCore import *
from PyQt6.QtGui import *
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog,QApplication,QFileDialog,QMainWindow,QComboBox
import sys
from Paste_table_vf import Paste_table_vf
from PyQt6.QtGui import QIcon

class Ui_MainWindow(object):
    def __init__(self):
        super(Ui_MainWindow,self).__init__()

    def Browsefiles(self):
        fname=QFileDialog.getOpenFileName(None,'open file','.')
        self.Filename.setText(fname[0])

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("DataProcessing")
        MainWindow.resize(815, 324)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 61))
        self.label.setObjectName("label")
        self.Filename = QtWidgets.QLineEdit(self.centralwidget)
        self.Filename.setGeometry(QtCore.QRect(70, 30, 551, 51))
        self.Filename.setObjectName("Filename")

        self.CopyData = QtWidgets.QPushButton(self.centralwidget)
        self.CopyData.setGeometry(QtCore.QRect(200, 100, 281, 41))
        self.CopyData.setAutoFillBackground(True)
        self.CopyData.setObjectName("CopyData")
        self.CopyData.setStyleSheet("background-color:green;\n"
                                      "color: white;\n"
                                      "border-style: outset;\n"
                                      "border-width:2px;\n"
                                      "border-radius:10px;\n"
                                      "border-color:black;\n"
                                      "font:bold 14px;\n"
                                      "padding :6px;\n"
                                      "min-width:10px;\n"
                                      "\n"
                                      "\n"
                                      "")
        self.CopyData.clicked.connect(self.paste)
       
        self.Browse = QtWidgets.QPushButton(self.centralwidget)
        self.Browse.setGeometry(QtCore.QRect(640, 30, 151, 51))
        self.Browse.setAutoFillBackground(True)
        self.Browse.setObjectName("Browse")
        self.Browse.setStyleSheet("background-color:red;\n"
                                      "color: white;\n"
                                      "border-style: outset;\n"
                                      "border-width:2px;\n"
                                      "border-radius:10px;\n"
                                      "border-color:black;\n"
                                      "font:bold 14px;\n"
                                      "padding :6px;\n"
                                      "min-width:10px;\n"
                                      "\n"
                                      "\n"
                                      "")
        self.Browse.clicked.connect(self.Browsefiles)

        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 26))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def paste(self):
        path=self.Filename.text()
        Paste_table_vf(path,True,[1],'DataRoom')
        print(' Done !! ')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dataprocessing"))
        self.label.setText(_translate("MainWindow", "Path : "))
        self.CopyData.setText(_translate("MainWindow", "CopyData"))
        self.Browse.setText(_translate("MainWindow", "Browse"))

if __name__== "__main__":
    import sys
    app=QtWidgets.QApplication(sys.argv)
    form=QtWidgets.QWidget()
    ui=Ui_MainWindow()
    ui.setupUi(form)
    # création d'un objet myCombo
    #Ui_MainWindow.build(form) 
    form.show()
    sys.exit(app.exec())

