# Form implementation generated from reading ui file 'CopyData.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from copy_paste_ranges import copy_paste_ranges
#from PyQt6.QtCore import list

class Ui_MainWindow(object):
    def Copydata(self):
        print("dazt")
        list=copy_paste_ranges()
        self.listWidget.addItem(list)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 270, 341, 61))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 40, 151, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.Copydata)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(420, 130, 301, 41))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 170, 211, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)
        # model=QtGui.QStringListModel()
        # model.setStringList(list)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "CopyData"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))

if __name__== "__main__":
    import sys
    CopyData=QtWidgets.QApplication(sys.argv)
    form=QtWidgets.QWidget()
    ui=Ui_MainWindow()
    ui.setupUi(form)
    form.show()
    sys.exit(CopyData.exec())
    



# void OpenXMLFile::on_File1Button_clicked()
# {
#     file1Name = QFileDialog::getOpenFileName(this,
#          tr("Open XML File 1"), "/home", tr("XML Files (*.xml)"));
#     ui->File1Path->setText(file1Name);

# }

# void OpenXMLFile::on_File2Button_clicked()
# {
#     file2Name = QFileDialog::getOpenFileName(this,
#          tr("Open XML File 2"), "/home", tr("XML Files (*.xml)"));
#     ui->File2Path->setText(file2Name);

# }