# Form implementation generated from reading ui file 'CopyData.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import win32com.client
from PyQt6.QtCore import *
from PyQt6.QtGui import *
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog,QApplication,QFileDialog,QMainWindow,QComboBox
from sorted_tab import sorted_tab
from my_head import my_head
import sys
from Paste_table_vf import Paste_table_vf
from PyQt6.QtGui import QIcon
from openpyxl import  load_workbook 
from Nb_tests import Nb_tests

class Ui_DataProcessing(object):

    def __init__(self):
        super(Ui_DataProcessing,self).__init__()

    def Browsefiles(self):
        fname=QFileDialog.getOpenFileName(None,'open file','.')
        self.Filename.setText(fname[0])
        path=self.Filename.text()
        sheets=Nb_tests(path)[0]
        self.comboBox.addItems(sheets)
         
    def setupUi(self, DataProcessing):
        DataProcessing.setObjectName("DataProcessing")
        DataProcessing.resize(922, 412)
        self.centralwidget = QtWidgets.QWidget(DataProcessing)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 131, 61))
        self.label.setObjectName("label")

        self.CopyData = QtWidgets.QPushButton(self.centralwidget)
        self.CopyData.setGeometry(QtCore.QRect(640, 90, 151, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)

        self.CopyData.setAutoFillBackground(True)
        self.CopyData.setObjectName("CopyData")
        self.CopyData.setStyleSheet("background-color:green;\n"
                                      "color: white;\n"
                                      "border-style: outset;\n"
                                      "border-width:2px;\n"
                                      "border-radius:10px;\n"
                                      "border-color:black;\n"
                                      "font:bold 14px;\n"
                                      "padding :6px;\n"
                                      "min-width:10px;\n"
                                      "\n"
                                      "\n"
                                      "")
        self.CopyData.clicked.connect(self.paste_vf)
       
        self.Browse = QtWidgets.QPushButton(self.centralwidget)
        self.Browse.setGeometry(QtCore.QRect(640, 30, 151, 51))
        self.Browse.setAutoFillBackground(True)
        self.Browse.setObjectName("Browse")
        self.Browse.setStyleSheet("background-color:red;\n"
                                      "color: white;\n"
                                      "border-style: outset;\n"
                                      "border-width:2px;\n"
                                      "border-radius:10px;\n"
                                      "border-color:black;\n"
                                      "font:bold 14px;\n"
                                      "padding :6px;\n"
                                      "min-width:10px;\n"
                                      "\n"
                                      "\n"
                                      "")
        self.Browse.clicked.connect(self.Browsefiles)
  
        self.Filename = QtWidgets.QLineEdit(self.centralwidget)
        self.Filename.setGeometry(QtCore.QRect(70, 30, 551, 51))
        self.Filename.setObjectName("Filename")

        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(290, 90, 150, 41))
        self.checkBox.setObjectName("checkBox")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(70, 90, 150, 31))
        self.comboBox.setObjectName("comboBox")
        
        self.menubar = QtWidgets.QMenuBar(DataProcessing)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 922, 26))
        self.menubar.setObjectName("menubar")

        self.statusbar = QtWidgets.QStatusBar(DataProcessing)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(DataProcessing)
        QtCore.QMetaObject.connectSlotsByName(DataProcessing)

    def retranslateUi(self, DataProcessing):
        _translate = QtCore.QCoreApplication.translate
        DataProcessing.setWindowTitle(_translate("DataProcessing", "DataProcessing"))
        self.label.setText(_translate("DataProcessing", "Path : "))
        self.CopyData.setText(_translate("DataProcessing", "CopyData"))
        self.Browse.setText(_translate("DataProcessing", "Browse"))
        self.checkBox.setText(_translate("DataProcessing", "xxC°:Ascending"))

    def paste_vf(self):
        path=self.Filename.text()
        B=self.checkBox.isChecked()
        DataRoom=self.comboBox.currentText()
        Paste_table_vf(path,B,[1],DataRoom)

if __name__== "__main__":
    import sys
    app=QtWidgets.QApplication(sys.argv)
    form=QtWidgets.QWidget()
    ui=Ui_DataProcessing()
    ui.setupUi(form)
    form.show()
    sys.exit(app.exec())